version: "3"

services:
  internal-gateway-api:
    image: internal-gateway-api:fri
    container_name: internal-gateway-api
    build:
      context: ../../
      dockerfile: ./src/WCloud.Member.InternalApi/Dockerfile
    restart: unless-stopped
    ports:
      - "18888:18888"
    networks:
      - xx
networks:
  xx:
    external:
      name: xx
