version: "3"

services:
  admin-vue:
    image: admin-vue:fri
    container_name: admin-vue
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - xx
networks:
  xx:
    external:
      name: xx
