name: publish-nuget

on:
  workflow_dispatch:

env:
  nuget_server: https://nuget.pkg.github.com/wcloud-net/index.json
  user_name: hiwjcn
  github_token: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
         nuget-version: latest
      
      - name: add-nuget-source
        run: 
          dotnet nuget add source ${nuget_server} --name GitHub --username ${user_name} --password ${github_token}
          nuget setapikey ${github_token} -Source ${nuget_server}
    
      - name: pack-and-push-lib
        working-directory: ./src/Lib/
        run: |
          dotnet pack -c Release
          dotnet nuget push ./bin/Release/*.nupkg --source GitHub --skip-duplicate
