name: publish-nuget

on:
  workflow_dispatch:

env:
  nuget_server: https://api.nuget.org/v3/index.json
  user_name: hiwjcn
  nuget_token: ${{secrets.NUGET_TOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
         nuget-version: latest

      - name: add-nuget-source
        run: |
          dotnet nuget add source ${nuget_server} --name nuget_org
          nuget setapikey ${nuget_token} -Source ${nuget_server}
    
      - name: pack-and-push-lib
        working-directory: ./src/Lib/
        run: |
          dotnet pack -c Release
          dotnet nuget push ./bin/Release/*.nupkg --source nuget_org --skip-duplicate
